"""initial schema

Revision ID: b49c51d5498b
Revises: 
Create Date: 2026-06-10 20:10:21.841877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b49c51d5498b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # btree_gist: sku_price 的 EXCLUDE 约束依赖；pg_trgm: 成品件/SKU 模糊搜索
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('can_set_price', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'sales')", name=op.f('ck_app_user_role_enum')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('username', name=op.f('uq_app_user_username'))
    )
    op.create_table('code_counter',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('kind', 'year', name=op.f('pk_code_counter'))
    )
    op.create_table('node_type',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('is_sellable_root', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code ~ '^[A-Z0-9_-]+$'", name=op.f('ck_node_type_code_charset')),
    sa.CheckConstraint("kind IN ('product', 'part')", name=op.f('ck_node_type_kind_enum')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_node_type')),
    sa.UniqueConstraint('code', name=op.f('uq_node_type_code'))
    )
    op.create_table('supplier',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code ~ '^[A-Z0-9_-]+$'", name=op.f('ck_supplier_code_charset')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier')),
    sa.UniqueConstraint('code', name=op.f('uq_supplier_code'))
    )
    op.create_table('attribute_def',
    sa.Column('node_type_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value_kind', sa.String(length=10), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_filterable', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code ~ '^[A-Z0-9_-]+$'", name=op.f('ck_attribute_def_code_charset')),
    sa.CheckConstraint("value_kind IN ('enum', 'number', 'text')", name=op.f('ck_attribute_def_value_kind_enum')),
    sa.ForeignKeyConstraint(['node_type_id'], ['node_type.id'], name=op.f('fk_attribute_def_node_type_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attribute_def')),
    sa.UniqueConstraint('node_type_id', 'code', name=op.f('uq_attribute_def_node_type_id_code'))
    )
    op.create_table('audit_log',
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['app_user.id'], name=op.f('fk_audit_log_actor_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('component_slot',
    sa.Column('parent_type_id', sa.BigInteger(), nullable=False),
    sa.Column('child_type_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('allow_blackbox', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code ~ '^[A-Z0-9_-]+$'", name=op.f('ck_component_slot_code_charset')),
    sa.ForeignKeyConstraint(['child_type_id'], ['node_type.id'], name=op.f('fk_component_slot_child_type_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_type_id'], ['node_type.id'], name=op.f('fk_component_slot_parent_type_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_component_slot')),
    sa.UniqueConstraint('id', 'child_type_id', name=op.f('uq_component_slot_id_child_type_id')),
    sa.UniqueConstraint('parent_type_id', 'code', name=op.f('uq_component_slot_parent_type_id_code'))
    )
    op.create_table('config_draft',
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('root_type_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], name=op.f('fk_config_draft_owner_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_type_id'], ['node_type.id'], name=op.f('fk_config_draft_root_type_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_draft'))
    )
    op.create_table('import_batch',
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('ok_rows', sa.Integer(), nullable=False),
    sa.Column('error_rows', sa.Integer(), nullable=False),
    sa.Column('report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('dry_run', 'committed', 'failed')", name=op.f('ck_import_batch_status_enum')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_import_batch_created_by'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batch'))
    )
    op.create_index('uq_import_batch_committed_file', 'import_batch', ['file_hash'], unique=True, postgresql_where="status = 'committed'")
    op.create_table('purchased_part',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('node_type_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('spec_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('merged_into_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'merged') = (merged_into_id IS NOT NULL)", name=op.f('ck_purchased_part_merged_target')),
    sa.CheckConstraint("code ~ '^[A-Z0-9_-]+$'", name=op.f('ck_purchased_part_code_charset')),
    sa.CheckConstraint("status IN ('draft', 'active', 'merged', 'retired')", name=op.f('ck_purchased_part_status_enum')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_purchased_part_created_by'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merged_into_id'], ['purchased_part.id'], name=op.f('fk_purchased_part_merged_into_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['node_type_id'], ['node_type.id'], name=op.f('fk_purchased_part_node_type_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], name=op.f('fk_purchased_part_supplier_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchased_part')),
    sa.UniqueConstraint('code', name=op.f('uq_purchased_part_code')),
    sa.UniqueConstraint('id', 'node_type_id', name=op.f('uq_purchased_part_id_node_type_id')),
    sa.UniqueConstraint('supplier_id', 'node_type_id', 'name', name=op.f('uq_purchased_part_supplier_id_node_type_id_name'))
    )
    op.create_table('quote',
    sa.Column('quote_no', sa.String(length=30), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_contact', sa.String(length=200), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_quote_currency_iso')),
    sa.CheckConstraint("status IN ('draft', 'exported')", name=op.f('ck_quote_status_enum')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_quote_created_by'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote')),
    sa.UniqueConstraint('quote_no', name=op.f('uq_quote_quote_no'))
    )
    op.create_table('attribute_option',
    sa.Column('attribute_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('numeric_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code ~ '^[A-Z0-9_-]+$'", name=op.f('ck_attribute_option_code_charset')),
    sa.ForeignKeyConstraint(['attribute_id'], ['attribute_def.id'], name=op.f('fk_attribute_option_attribute_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attribute_option')),
    sa.UniqueConstraint('attribute_id', 'code', name=op.f('uq_attribute_option_attribute_id_code')),
    sa.UniqueConstraint('attribute_id', 'id', name=op.f('uq_attribute_option_attribute_id_id'))
    )
    op.create_table('sku',
    sa.Column('sku_code', sa.String(length=30), nullable=False),
    sa.Column('root_type_id', sa.BigInteger(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('import_batch_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'retired')", name=op.f('ck_sku_status_enum')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_sku_created_by'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], name=op.f('fk_sku_import_batch_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['root_type_id'], ['node_type.id'], name=op.f('fk_sku_root_type_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sku')),
    sa.UniqueConstraint('fingerprint', name=op.f('uq_sku_fingerprint')),
    sa.UniqueConstraint('sku_code', name=op.f('uq_sku_sku_code'))
    )
    op.create_table('quote_item',
    sa.Column('quote_id', sa.BigInteger(), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('snapshot_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('line_note', sa.String(length=300), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('qty > 0', name=op.f('ck_quote_item_qty_positive')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_quote_item_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.id'], name=op.f('fk_quote_item_quote_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], name=op.f('fk_quote_item_sku_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote_item')),
    sa.UniqueConstraint('quote_id', 'sku_id', name=op.f('uq_quote_item_quote_id_sku_id'))
    )
    op.create_table('sku_config_node',
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_node_id', sa.BigInteger(), nullable=True),
    sa.Column('slot_id', sa.BigInteger(), nullable=True),
    sa.Column('node_type_id', sa.BigInteger(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('purchased_part_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint("(mode = 'purchased') = (purchased_part_id IS NOT NULL)", name=op.f('ck_sku_config_node_purchased_part_presence')),
    sa.CheckConstraint("mode IN ('configured', 'purchased')", name=op.f('ck_sku_config_node_mode_enum')),
    sa.CheckConstraint('(parent_node_id IS NULL) = (slot_id IS NULL)', name=op.f('ck_sku_config_node_root_no_slot')),
    sa.ForeignKeyConstraint(['node_type_id'], ['node_type.id'], name=op.f('fk_sku_config_node_node_type_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_node_id'], ['sku_config_node.id'], name=op.f('fk_sku_config_node_parent_node_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchased_part_id', 'node_type_id'], ['purchased_part.id', 'purchased_part.node_type_id'], name='fk_node_part_type_match', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], name=op.f('fk_sku_config_node_sku_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id', 'node_type_id'], ['component_slot.id', 'component_slot.child_type_id'], name='fk_node_slot_type_match', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sku_config_node')),
    sa.UniqueConstraint('sku_id', 'parent_node_id', 'slot_id', name=op.f('uq_sku_config_node_sku_id_parent_node_id_slot_id'))
    )
    op.create_index('uq_sku_config_node_single_root', 'sku_config_node', ['sku_id'], unique=True, postgresql_where='parent_node_id IS NULL')
    op.create_table('sku_price',
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.text('sku_id'), '='), (sa.text('currency'), '='), (sa.text("daterange(valid_from, valid_to, '[]')"), '&&'), using='gist', name='excl_sku_price_overlap'),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_sku_price_currency_iso')),
    sa.CheckConstraint('price >= 0', name=op.f('ck_sku_price_price_non_negative')),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name=op.f('ck_sku_price_valid_range_order')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_sku_price_created_by'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sku_id'], ['sku.id'], name=op.f('fk_sku_price_sku_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sku_price'))
    )
    op.create_table('sku_attribute_value',
    sa.Column('config_node_id', sa.BigInteger(), nullable=False),
    sa.Column('attribute_id', sa.BigInteger(), nullable=False),
    sa.Column('option_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['attribute_id', 'option_id'], ['attribute_option.attribute_id', 'attribute_option.id'], name='fk_value_option_of_attribute', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['config_node_id'], ['sku_config_node.id'], name=op.f('fk_sku_attribute_value_config_node_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sku_attribute_value')),
    sa.UniqueConstraint('config_node_id', 'attribute_id', name=op.f('uq_sku_attribute_value_config_node_id_attribute_id'))
    )
    # ### end Alembic commands ###

    # 模糊搜索索引（pg_trgm）
    op.execute(
        "CREATE INDEX ix_purchased_part_name_trgm ON purchased_part USING gin (name gin_trgm_ops)"
    )
    op.execute("CREATE INDEX ix_sku_name_trgm ON sku USING gin (name gin_trgm_ops)")

    # 当前价视图：每 SKU 每币种取今日生效的价格记录（EXCLUDE 约束保证至多一条）
    op.execute(
        """
        CREATE VIEW v_sku_current_price AS
        SELECT sp.sku_id, sp.currency, sp.price, sp.valid_from, sp.valid_to, sp.id AS price_id
        FROM sku_price sp
        WHERE sp.valid_from <= CURRENT_DATE
          AND (sp.valid_to IS NULL OR sp.valid_to >= CURRENT_DATE)
        """
    )


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS v_sku_current_price")
    op.execute("DROP INDEX IF EXISTS ix_sku_name_trgm")
    op.execute("DROP INDEX IF EXISTS ix_purchased_part_name_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sku_attribute_value')
    op.drop_table('sku_price')
    op.drop_index('uq_sku_config_node_single_root', table_name='sku_config_node', postgresql_where='parent_node_id IS NULL')
    op.drop_table('sku_config_node')
    op.drop_table('quote_item')
    op.drop_table('sku')
    op.drop_table('attribute_option')
    op.drop_table('quote')
    op.drop_table('purchased_part')
    op.drop_index('uq_import_batch_committed_file', table_name='import_batch', postgresql_where="status = 'committed'")
    op.drop_table('import_batch')
    op.drop_table('config_draft')
    op.drop_table('component_slot')
    op.drop_table('audit_log')
    op.drop_table('attribute_def')
    op.drop_table('supplier')
    op.drop_table('node_type')
    op.drop_table('code_counter')
    op.drop_table('app_user')
    # ### end Alembic commands ###
